--liquibase formatted sql
--changeset mihai:004-add-audit-columns

-- Add audit columns to employees table
ALTER TABLE IF EXISTS employees
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

-- Add audit columns to actors table
ALTER TABLE IF EXISTS actors
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

-- Add audit columns to movies table
ALTER TABLE IF EXISTS movies
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(100),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

--rollback ALTER TABLE employees DROP COLUMN IF EXISTS created_at, DROP COLUMN IF EXISTS created_by, DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS updated_by;
--rollback ALTER TABLE actors DROP COLUMN IF EXISTS created_at, DROP COLUMN IF EXISTS created_by, DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS updated_by;
--rollback ALTER TABLE movies DROP COLUMN IF EXISTS created_at, DROP COLUMN IF EXISTS created_by, DROP COLUMN IF EXISTS updated_at, DROP COLUMN IF EXISTS updated_by;

