db.url=jdbc:sqlite:C:\\Facultate\\Anul_2\\Semestru_2\\SGBD\\Proect_Lab123\\identifier.sqlite
db.username=
db.password=

# PostgreSQL connection used by Transaction Lab module
lab.db.url=jdbc:postgresql://localhost:5432/sgbd_lab
lab.db.username=postgres
lab.db.password=postgres
